version: "3.0"
services:

  django_app:
    image: koushema/helloworld2
    ports:
      - "8000:8000"
    depends_on:
      - redis_server
    environment:
      - DJANGO_BACKEND_SECRET_KEY
      - DB
      - DB_HOST
      - DB_PORT
      - DB_PASS

  redis_server:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command:
      --requirepass ${DB_PASS}
