version: "3.0"
services:
  web:
    image: koushema/helloworld:v1.0
    ports:
      - "8000:8000"
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    command: >
      --requirepass ${REDIS_PASSWORD}
